version: '3'
services:
  iobroker:
    build: 
      context: .
    privileged: true
    ports:
      - 8081:8081
    volumes:
      - ./volume/:/opt/iobroker/
    environment:
      PACKAGES: 'ioBroker.lupusec'
      AVAHI: 'false'
